version: "3.8"

services:
  postgres:
    image: "postgres:16.2"
    container_name: "devops-test-postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jjerome
      - POSTGRES_PASSWORD=jjerome
